<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Starten',
    'stopping' => 'Stoppen',
    'suspended' => 'Suspendiert',
    'connection-error' => 'Verbindungsfehler',
    'transferring' => 'Übertragen',
    'installing' => 'Installieren',
    'restoring-backup' => 'Wiederherstellen aus Backup',
    'unavailable' => 'Nicht erreichbar',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'RAM',
    'disk' => 'Festplatte',
    'unlimited' => 'Unbegrenzt',
    'start' => 'Start',
    'restart' => 'Neustart',
    'stop' => 'Stop',
    'kill' => 'Kill',
    'forcibly-stop-process' => 'Stoppen erzwingen',
    'continue' => 'Fortfahren',
    'forcibly-stopping-alert' => 'Stoppen des Servers zu erzwingen kann zu Schäden an den Dateien führen.',
    'cpu-usage' => 'CPU Verbrauch',
    'memory-usage' => 'RAM Verbrauch',
    'disk-usage' => 'Festplatten Verbrauch',
    'inbound-outbound' => 'Input / Output',
    'low-resources' => 'Freie Ressourcen sind niedrig',
    'low-resources-desc' => 'Dein Server hat nur noch wenige freie Ressourcen, upgrade deinen Server falls möglich.',
    'upgrade-server' => 'Server upgraden',
    'cancel' => 'Abbrechen',
    'copied-text' => '{{text}} wurde in die Zwischenablage kopiert.',
    'showing' => 'Zeigen',
    'to' => 'zu',
    'of' => 'von',
    'results' => 'Ergebnisse.',
];
