<?php

return [
    'file-manager' => 'Dateimanager',
    'search' => 'Suchen',
    'delete' => 'Löschen',
    'move' => 'Verschieben',
    'archive' => 'Archivieren',
    'unarchive' => 'Entpacken',
    'create-directory' => 'Verzeichnis erstellen',
    'upload' => 'Hochladen',
    'new-file' => 'Neue Datei',
    'rename' => 'Umbenennen',
    'permissions' => 'Berechtigungen',
    'copy' => 'Kopieren',
    'download' => 'Herunterladen',
    'update' => 'Aktualisieren',
    'file-mode' => 'Dateimodus',
    'you-cant-recover' => 'Du kannst den Inhalt nicht wiederherstellen, wenn',
    'once-deleted' => einmal gelöscht ist.',
    'delete-files' => 'Dateien löschen',
    'are-you-sure' => 'Bist du dir sicher, dass du dies löschen möchtest?',
    'this-is-permanent-action' => 'Dies ist eine permanente Aktion und die Dateien können nicht wiederhergestellt werden.',
    'name' => 'Name',
    'Größe' => 'Größe',
    'Datum' => 'Datum',
    'home' => 'Home',
    'container' => 'Container',
    'is-empty' => 'Dieses Verzeichnis scheint leer zu sein.',
    'is-limited' => 'Dieses Verzeichnis ist zu groß, um es im Browser anzuzeigen, daher wird die Ausgabe auf die ersten 250 Dateien begrenzt.',
    'are-upload-click-to-view' => 'Dateien werden hochgeladen, klicke zum anzeigen.',
    'cancel-uploads' => 'Uploads abbrechen',
    'cancel' => 'Abbrechen',
    'close' => 'Schließen',
    'create' => 'Erstellen',
    'file-name' => 'Dateiname',
    'file-name-description' => 'Gib den Namen ein, unter dem diese Datei gespeichert werden soll.',
    'directory-will-be-as' => 'Dieses Verzeichnis wird erstellt als',
    'rename-description' => 'Gib den neuen Namen und das neue Verzeichnis dieser Datei oder dieses Ordners ein, relativ zum aktuellen Verzeichnis.',
    'new-location' => 'Neuer Ort',
    'drag-and-drop' => 'Ziehe die Dateien zum Hochladen per Drag and Drop.',

    'edit' => [
        'youre-editing' => 'Du bearbeitest',
        'will-be-exluded' => 'Alle Dateien oder Verzeichnisse, die hier aufgeführt sind, werden vom Backup ausgeschlossen. Wildcards werden durch die Verwendung eines Sternchens unterstützt',
        'you-can-negate' => 'Du kannst eine vorherige Regel negieren, indem du ein Ausrufezeichen voranstellst',
        'save-content' => 'Inhalt speichern',
        'create-file' => 'Datei erstellen',
    ],
];
